export type Service = { number:string; title:string; description:string; detail:string };
export type Material = { name:string; origin:string; finish:string; tone:string };
export type Testimonial = { quote:string; name:string; context:string };
export const services:Service[]=[{number:'01',title:'Interior architecture',description:'We rethink the plan before we pick the paint.',detail:'Spatial planning, considered joinery, lighting layouts and architectural detailing for renovations and new homes.'},{number:'02',title:'Full-service interiors',description:'A complete home, carried through with care.',detail:'From the first site measure to the final art placement, we coordinate design, sourcing, procurement and installation.'},{number:'03',title:'Furniture & objects',description:'Pieces with a point of view and a place to belong.',detail:'Bespoke furniture, vintage finds and useful objects selected for proportion, provenance and longevity.'},{number:'04',title:'Styling & consultation',description:'A thoughtful edit for a home already in motion.',detail:'Focused consultations and finishing sessions for existing spaces that need a clearer, more personal direction.'}];
export const materials:Material[]=[{name:'Tumbled travertine',origin:'Rajasthan, India',finish:'Honed · filled',tone:'#b8a58f'},{name:'Smoked white oak',origin:'Responsibly sourced',finish:'Brushed · oil wax',tone:'#705a49'},{name:'Handloom khadi',origin:'Kutch, Gujarat',finish:'Washed · natural',tone:'#d8d0c0'},{name:'Antique brass',origin:'Moradabad, India',finish:'Hand patinated',tone:'#aa855b'},{name:'Lime plaster',origin:'Artisan mixed',finish:'Soft matte · warm white',tone:'#e5dfd2'}];
export const testimonials:Testimonial[]=[{quote:'They listened to how we actually live before they drew a single line. The result feels unmistakably ours, and somehow calmer than we imagined.',name:'Ananya & Rohan',context:'The Quiet House · Alibaug'},{quote:'Every decision felt considered, never precious. Our home is beautiful, but the best part is how naturally it works on an ordinary Tuesday.',name:'Meera Shah',context:'Courtyard Light · Mumbai'}];
export const imageUrl=(id:string,width=1600)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;


