export type InteriorStyle = {
  name: string;
  descriptor: string;
  image: string;
  description: string;
  palette: { name: string; color: string }[];
  materials: string[];
  furniture: string;
  lighting: string;
};

export const interiorStyles: InteriorStyle[] = [
  { name: 'Minimalist', descriptor: 'Less, with intention', image: 'photo-1600210492486-724fe5c67fb0', description: 'A quieter way to live, where proportion, daylight and a considered edit give every object room to matter.', palette: [{ name: 'Chalk', color: '#e8e3d9' }, { name: 'Putty', color: '#c9c0b2' }, { name: 'Charcoal', color: '#42413d' }], materials: ['Limewash plaster', 'Pale oak', 'Washed linen'], furniture: 'Low profiles, clean silhouettes and a few sculptural forms, chosen for comfort as much as clarity.', lighting: 'Layered daylight, concealed architectural light and restrained warm accents.' },
  { name: 'Modern', descriptor: 'Clarity in every line', image: 'photo-1600607687939-ce8a6c25118c', description: 'Crisp geometry meets natural tactility in rooms designed around openness, function and lasting form.', palette: [{ name: 'Warm white', color: '#e9e5dc' }, { name: 'Stone', color: '#aaa49a' }, { name: 'Blackened bronze', color: '#4b4842' }], materials: ['Travertine', 'Smoked oak', 'Brushed metal'], furniture: 'Architectural profiles, tailored upholstery and purposeful pieces with a strong sense of proportion.', lighting: 'Precise recessed lighting balanced by sculptural pendants and quiet indirect glow.' },
  { name: 'Japandi', descriptor: 'Calm, held in balance', image: 'photo-1600566753086-00f18fb6b3ea', description: 'The ease of Japanese restraint meets the warmth of Nordic living through natural texture and mindful simplicity.', palette: [{ name: 'Rice paper', color: '#e4ddcf' }, { name: 'Mushroom', color: '#b8a893' }, { name: 'Moss', color: '#747763' }], materials: ['White oak', 'Handmade ceramic', 'Woven hemp'], furniture: 'Grounded, low-set forms with honest joinery, soft edges and generous negative space.', lighting: 'Soft diffused light, paper shades and warm pools of illumination at human scale.' },
  { name: 'Scandinavian', descriptor: 'Light, made welcoming', image: 'photo-1600607687920-4e2a09cf159d', description: 'An open, practical warmth that makes the most of natural light and turns everyday rituals into comfort.', palette: [{ name: 'Snow', color: '#efede6' }, { name: 'Birch', color: '#d1b998' }, { name: 'Dusty blue', color: '#8d9da0' }], materials: ['Birch timber', 'Bouclé wool', 'Natural stone'], furniture: 'Functional, softly rounded pieces with exposed timber, inviting upholstery and an unforced feel.', lighting: 'Reflective natural light with layered floor lamps and intimate table lights for darker hours.' },
  { name: 'Contemporary', descriptor: 'Of the moment, enduring', image: 'photo-1600607687644-c7171b42498f', description: 'A fluid mix of current form and enduring craft, shaped to feel personal rather than prescribed.', palette: [{ name: 'Ivory', color: '#e8e1d5' }, { name: 'Clay', color: '#b77f68' }, { name: 'Ink', color: '#3a3b39' }], materials: ['Veined stone', 'Walnut', 'Textured wool'], furniture: 'A balance of tailored classics and expressive silhouettes, anchored by tactile upholstery.', lighting: 'A flexible scheme that combines clean architectural lines with statement decorative fixtures.' },
  { name: 'Industrial', descriptor: 'A softer kind of edge', image: 'photo-1600566753190-17f0baa2a6c3', description: 'Raw architectural character is refined with warmth, craft and a deliberate contrast of surfaces.', palette: [{ name: 'Concrete', color: '#98958e' }, { name: 'Oxide', color: '#8a5d47' }, { name: 'Coal', color: '#393a38' }], materials: ['Board-formed concrete', 'Reclaimed timber', 'Aged steel'], furniture: 'Robust, generously scaled pieces softened by natural textiles and considered vintage finds.', lighting: 'Directional task lighting, dark metal pendants and warm ambient layers.' },
  { name: 'Luxury', descriptor: 'Quietly exceptional', image: 'photo-1600210492486-724fe5c67fb0', description: 'A deeply considered expression of comfort, where material quality and exacting detail speak softly.', palette: [{ name: 'Champagne', color: '#d8c9ae' }, { name: 'Marble', color: '#e3dfd7' }, { name: 'Bronze', color: '#806a50' }], materials: ['Calacatta marble', 'Book-matched walnut', 'Patinated bronze'], furniture: 'Made-to-measure forms, exceptional upholstery and one-of-a-kind pieces with enduring presence.', lighting: 'Dimmable, layered light that reveals material depth and creates a composed evening mood.' },
  { name: 'Biophilic', descriptor: 'Closer to the living world', image: 'photo-1600607687939-ce8a6c25118c', description: 'Spaces that restore their connection to nature through daylight, planting and materials with a sense of origin.', palette: [{ name: 'Limestone', color: '#ded7c9' }, { name: 'Leaf', color: '#71806b' }, { name: 'Earth', color: '#94765b' }], materials: ['Honest timber', 'Natural stone', 'Linen and rattan'], furniture: 'Organic shapes, tactile natural fibres and pieces that sit comfortably alongside living greenery.', lighting: 'Daylight first, with warm, low-glare layers that support the changing rhythm of the day.' },
];

